package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.Hyperlink;

public class UserCreatedController {
	@FXML
	private AnchorPane rootPane;
	@FXML
	private Hyperlink login;

	// Event Listener on Hyperlink[#login].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
		try {	
    		AnchorPane 	root=(AnchorPane)FXMLLoader.load(getClass().getResource("Categories.fxml"));
	    	rootPane.getChildren().setAll(root);
    	}
    	catch(Exception e){
    		e.printStackTrace();
		}
	}
}
